[versions]
core-ktx = "1.9.0"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
material = "1.9.0"
junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso = "3.5.1"
androidx-lifecycle = "2.2.0"
androidx-lifecycle-runtime = "2.6.2"
androidx-viewmodel = "2.6.2"
kotlinx-coroutines-android = "1.7.2"
kotlinx-coroutines-core = "1.7.2"
dagger-hilt = "2.48.1"
dagger-hilt-compiler = "2.48.1"
dagger-hilt-navigation = "1.0.0"
androidx-compose = "1.7.2"
androidx-compose-viewmodel = "2.6.1"

[libraries]
androidx-compose-bom = "androidx.compose:compose-bom:2023.10.01"
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-compose" }
androidx-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-compose-viewmodel" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }

androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-viewmodel" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }

dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt-compiler" }
dagger-hilt-navigation = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "dagger-hilt-navigation" }